# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-09-04 07:51-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/handlers/http_error.py:67
msgid "Not authenticated"
msgstr "未认证"

#: src/handlers/http_error.py:79
msgid "Internal Server Error"
msgstr "服务器内部错误"

#: src/services/authentication.py:32 src/services/authentication.py:34
#: src/services/authentication.py:39
msgid "invalid access token"
msgstr "无效的访问令牌"

#: src/services/authentication.py:58 src/services/authentication.py:64
msgid "invalid username or password"
msgstr "无效的用户名或密码"

#: src/services/authentication.py:61
msgid "this user has been disabled"
msgstr "此用户已被禁用"

#: src/routers/role.py:37 src/routers/role.py:53 src/routers/role.py:85
#, fuzzy
msgid "role not found"
msgstr "没有找到此角色"

#: src/routers/role.py:69
#, fuzzy
msgid "bad role name"
msgstr "无效的角色名称"

#: src/routers/users.py:25 src/routers/users.py:54 src/routers/users.py:77
#: src/routers/users.py:101
msgid "current user not found"
msgstr "没找到当前用户"

#: src/routers/users.py:62 src/routers/users.py:86 src/routers/users.py:106
msgid "user not found"
msgstr "没有找到此用户"

#: src/routers/users.py:81
msgid "not allowed delete current user"
msgstr "不允许删除当前用户"

#: src/routers/users.py:111
#, fuzzy
msgid "username already exists"
msgstr "用户名已存在"

#: src/routers/permission.py:37 src/routers/permission.py:53
#: src/routers/permission.py:90
#, fuzzy
msgid "permission not found"
msgstr "没有找到此权限"

#: src/routers/permission.py:69
#, fuzzy
msgid "bad permission name"
msgstr "无效的权限名称"

#: src/routers/permission.py:71
#, fuzzy
msgid "bad permission uri"
msgstr "无效的权限 URL"

#: src/routers/role_permission.py:37 src/routers/role_permission.py:53
#: src/routers/role_permission.py:89
#, fuzzy
msgid "role_permission not found"
msgstr "没有找到此角色权限"

#: src/routers/role_permission.py:70
#, fuzzy
msgid "bad role_permission role_id"
msgstr "无效的角色 ID"

#: src/routers/role_permission.py:72
#, fuzzy
msgid "bad role_permission permission_id"
msgstr "无效的权限 ID"

#: src/routers/user_group.py:37 src/routers/user_group.py:53
#: src/routers/user_group.py:87
#, fuzzy
msgid "user_group not found"
msgstr "没有找到此用户组"

#: src/routers/user_group.py:69
#, fuzzy
msgid "bad user_group name"
msgstr "无效的用户组名称"

#: src/routers/user_group.py:71
#, fuzzy
msgid "bad user_group creator"
msgstr "无效的用户组创建者"

#: src/routers/user_role.py:37 src/routers/user_role.py:53
#: src/routers/user_role.py:87
#, fuzzy
msgid "user_role not found"
msgstr "没有找到此角色的用户"

#: src/routers/user_role.py:69
msgid "bad user_role user_id"
msgstr "无效的用户 ID"

#: src/routers/user_role.py:71
msgid "bad user_role role_id"
msgstr "无效的角色 ID"

#: src/routers/login_log.py:38 src/routers/login_log.py:54
#, fuzzy
msgid "login_log not found"
msgstr "没有找到此角色"

#: src/routers/login_log.py:70
#, fuzzy
msgid "bad login_log user_id"
msgstr "无效的用户 ID"

#: src/routers/login_log.py:72
#, fuzzy
msgid "bad login_log status"
msgstr "无效的用户 ID"

#: src/routers/register.py:26
msgid "user with this username already exists"
msgstr "用户名已存在"

#: src/routers/register.py:29
msgid "user with this email already exists"
msgstr "邮箱已存在"
