# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-08-29 04:58-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/handlers/http_error.py:67
msgid "Not authenticated"
msgstr ""

#: src/handlers/http_error.py:79
msgid "Internal Server Error"
msgstr ""

#: src/services/authentication.py:33 src/services/authentication.py:35
#: src/services/authentication.py:40
msgid "invalid access token"
msgstr ""

#: src/services/authentication.py:63 src/services/authentication.py:69
msgid "invalid username or password"
msgstr ""

#: src/services/authentication.py:66
msgid "this user has been disabled"
msgstr ""

#: src/routers/role.py:37 src/routers/role.py:53 src/routers/role.py:85
msgid "role not found"
msgstr ""

#: src/routers/role.py:69
msgid "bad role name"
msgstr ""

#: src/routers/users.py:25 src/routers/users.py:54 src/routers/users.py:77
#: src/routers/users.py:101
msgid "current user not found"
msgstr ""

#: src/routers/users.py:62 src/routers/users.py:86 src/routers/users.py:106
msgid "user not found"
msgstr ""

#: src/routers/users.py:81
msgid "not allowed delete current user"
msgstr ""

#: src/routers/users.py:111
msgid "username already exists"
msgstr ""

#: src/routers/permission.py:37 src/routers/permission.py:53
#: src/routers/permission.py:89
msgid "permission not found"
msgstr ""

#: src/routers/permission.py:69
msgid "bad permission name"
msgstr ""

#: src/routers/permission.py:71
msgid "bad permission uri"
msgstr ""

#: src/routers/role_permission.py:37 src/routers/role_permission.py:53
#: src/routers/role_permission.py:89
msgid "role_permission not found"
msgstr ""

#: src/routers/role_permission.py:70
msgid "bad role_permission role_id"
msgstr ""

#: src/routers/role_permission.py:72
msgid "bad role_permission permission_id"
msgstr ""

#: src/routers/user_role.py:37 src/routers/user_role.py:53
#: src/routers/user_role.py:87
msgid "user_role not found"
msgstr ""

#: src/routers/user_role.py:69
msgid "bad user_role user_id"
msgstr ""

#: src/routers/user_role.py:71
msgid "bad user_role role_id"
msgstr ""

#: src/routers/register.py:26
msgid "user with this username already exists"
msgstr ""

#: src/routers/register.py:29
msgid "user with this email already exists"
msgstr ""
